version: "3.5"

volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts: 
      device: /home/ie-laabb/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts: 
      device: /home/ie-laabb/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception

services:

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  redis:
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - "8181:8181"
    networks:
      - inception
    env_file:
      - .env
    restart: always

  cadvisor:
    image: cadvisor
    container_name: cadvisor
    build : ./requirements/bonus/cadvisor
    ports:
     - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception
    restart: always

  website:
    image: website
    container_name: website
    build : ./requirements/bonus/website
    ports:
      - "3000:3000"
    networks:
      - inception
    restart: always