version: "3.3"

# volumes:
  # mariadb:
  #   name: mariadb=
#   wordpress:
#     name: wordpress

services:

  # nginx:
  #   image: nginx
  #   build: ./requirements/nginx/
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     # wordpress: 
  #   restart: always

  mariadb:
    image: mariadb
    build: ./requirements/mariadb/
    # volumes:
    #   - mariadb:/home/ie-laabb/data/mariadb
    restart: always

  # wordpress:
  #   image: wordpress
  #   build: ./requirements/wordpress/
  #   volumes:
  #     # - wordpress:/
  #   depends_on:
  #     - mariadb
  #   restart: always
