version: "3.5"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts: 
      device: /home/ie-laabb/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts: 
      device: /home/ie-laabb/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception

services:

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
