version: "3.5"

volumes:
  mariadb:
  wordpress:
#     name: mariadb
#     drive: local
#     drive_opts:
#       device: /home/ie-laabb/data/mariadb
#       o: bind
#       type: none

networks:
  inception:
    name: mariadb

services:

  # nginx:
  #   image: nginx
  #   build: ./requirements/nginx/
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - wordpress
  #   env_file:
  #     - .env
  #   # volumes:
  #     # wordpress: 
  #   restart: always

  wordpress:
    image: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/lib/php
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
